name: Pipeline CI-CD ULEAM

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno de ejecucion Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependencias del proyecto
        run: npm install

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno de ejecucion Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias esenciales
        run: npm install

      - name: Ejecutar la suite de pruebas automatizadas
        run: npx jest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Notificar y disparar actualizacion del servidor en Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"